version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3-jessie
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: bundle install
      - run: bash automated_build.sh
